### ISSUE TITLE
Export to OpenAPI

### ISSUE THREAD

**Issue by o-rey** [jsightapi/online-editor-frontend#218]
One of the huge advantages of OpenAPI scheme is the ability to use it with third-party instruments like Postman.
It would be supercool to have some kind of export inner format to OpenAPI v3

**Comment by andrew-platonov** [comment]
Thanks! This is already planned. We will account your request and try to boost the release.

**Comment by andrew-platonov** [comment]
Done in v. 6.0! 
See https://jsight.io/products/jsight-online-editor/release-notes#release-60
